#!/bin/bash

rm MQCT_SOURCE_CODES/*.o

module purge;
module load openmpi-geib-cuda10.2-intel/4.0.5 ;

mpifort -c -g -traceback ./MQCT_SOURCE_CODES/head.f -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;
mv *.o ./MQCT_SOURCE_CODES/;
mv *.mod ./MQCT_SOURCE_CODES/;
