#!/bin/bash

rm mqct_*

module purge;
module load openmpi-geib-cuda10.2-intel/4.0.5 ;

#executable of nitrogen_oxygen (N2+O) system_type = 1 or 2
mpifort -g -traceback -o mqct_N2_O ./MQCT_SOURCE_CODES/*.o ./PES_DIRECTORIES/PES_N2O/*.o -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;

#executable of benzene_helium (C6H6+He) system_type = 3
mpifort -g -traceback -o mqct_C6H6_He ./MQCT_SOURCE_CODES/*.o ./PES_DIRECTORIES/PES_C6H6_He/*.o -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;

#executable of water_Helium (H2O+He) system_type = 4
mpifort -g -traceback -o mqct_H2O_He ./MQCT_SOURCE_CODES/*.o ./PES_DIRECTORIES/PES_H2OHe/*.o -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;

#executable of methyl_formate_helium (CH3COOH+He) system_type = 4
mpifort -g -traceback -o mqct_CH3COOH_He ./MQCT_SOURCE_CODES/*.o ./PES_DIRECTORIES/PES_CH3COOH_He/*.o -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;

#executable of ammonia_H2 (ND3+D2) system_type = 7
mpifort -g -traceback -o mqct_ND3_D2 ./MQCT_SOURCE_CODES/*.o ./PES_DIRECTORIES/PES_ND3D2/*.o -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;

#executable of water_H2 (H2O+H2) system_type = 8
mpifort -g -traceback -o mqct_H2O_H2 ./MQCT_SOURCE_CODES/*.o ./PES_DIRECTORIES/PES_H2OH2/*.o -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;

#executable of water_NH3 (H2O+NH3) system_type = 9
mpifort -g -traceback -o mqct_NH3_H2O ./MQCT_SOURCE_CODES/*.o ./PES_DIRECTORIES/PES_NH3_H2O/*.o -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;

#executable of water_water (H2O+H2O) system_type = 0
mpifort -g -traceback -o mqct_H2O_H2O ./MQCT_SOURCE_CODES/*.o ./PES_DIRECTORIES/PES_H2OH2O/*.o -liomp5 -lmkl_intel_thread -lmkl_rt -lmkl_core -lmkl_intel_lp64 -lmkl_blacs_intelmpi_lp64 -lmkl_scalapack_lp64 ;
